<?php

return [
    'skip-route-function' => true,
    'groups' => [
        'admin' => [
            'admin.*',
            'auth.*',
            'locale.*',
            'user.*',
            'user-profile.*',
            'settings.*',
            'ip.*',
            'grid.*',
            'global.*',
            'token.*',
        ],
        'main' => [
            'auth.*',
            'admin.user.*',
            'admin.role.*',
            'email-verification.send',
            'exchange-trade.*',
            'commerce-account.*',
            'commerce-transaction.*',
            'commerce-customer.*',
            'commerce-payment.*',
            'locale.*',
            'user.*',
            'user-profile.*',
            'settings.*',
            'ip.*',
            'grid.*',
            'global.*',
            'wallet.*',
            'transfer-record.*',
            'wallet-account.*',
            'token.*',
            'feature-limit.*',
            'stake-plan.*',
            'stake.*',
            'payment.*',
            'giftcard.*',
            'giftcard-content.*',
            'giftcard-brand.*',
            'peer-payment.*',
            'peer-payment-method.*',
            'peer-offer.*',
            'peer-trade.*',
            'bank.*',
            'bank-account.*',
        ],
        'commerce-payment' => [
            'page.commerce-payment.*',
            'locale.*',
            'settings.*',
            'ip.*',
        ],
        'installer' => [
            'installer.*',
        ],
    ],
];
